### ISSUE TITLE
Can mongo-jdbc-driver be used in commercial software?

### ISSUE THREAD

**Issue by iirekm** [wise-coders/mongodb-jdbc-driver#11]
The license is unclear to me:
- https://github.com/wise-coders/mongodb-jdbc-driver/blob/master/License.txt looks like Apache License (i.e. can be used in commercial software)
- README.md mentions about GPL3 (which in most cases can't be used in commercial software without publishing commercial software source code)

How is that, can mongodb-jdbc-driver be used in commercial software (just as JDBC driver JAR, no driver's source code modifications), or not?

**Comment by wise-coders** [comment]
You can use the driver in commercial software, without publishing the source code. We will modify the README.md. We intend to allow modifications only in the actual GIT repository ( not cloning ). Do you know the best approach for this?
