### ISSUE TITLE
Java::JavaLang::UnsupportedClassVersionError

### ISSUE THREAD

**Issue by Dongzhenpu** [wise-coders/mongodb-jdbc-driver#12]
Hi, I'm going to test sync mongo data to es using logstash-input-jdbc, I found [here](https://dbschema.com/jdbc-driver/MongoDb.html) said `The driver is compatible with Java 8`, but when I use this [Driver](https://dbschema.com/jdbc-drivers/MongoDbJdbcDriver.zip) in logstash, I saw the following error logs:

`Java::JavaLang::UnsupportedClassVersionError: org/graalvm/polyglot/proxy/ProxyObject has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

does this mean the driver now only compatible with JAVA 11? or is there any other solution?

**Comment by wise-coders** [comment]
We updated the page and set Java 11 as a compatible version. The latest GraalVM libraries which are used in this project require Java 11.

**Comment by Dongzhenpu** [comment]
and update README.md BTW.

**Comment by HoracioDos** [comment]
Hello. Where can we find an old version that can be compatible with class file versions 52.0
Thanks in advance

**Comment by wise-coders** [comment]
Unfortunatelly we do not keep the backward compatibility with Java 8.
