### ISSUE TITLE
SSL support for passing cert along with the connections string

### ISSUE THREAD

**Issue by rehantoday** [wise-coders/mongodb-jdbc-driver#14]
Does this driver support SSL? If so, then how can we pass it the cert?
for example:

`jdbc_connection_string => "jdbc:mongodb://user:password@localhost:27017/testDb?authMechanism=DEFAULT&tls=true&tlsCAFile=/home/ca-bundle.pem"`

but this doesn't work. Is there any other way?

**Comment by wise-coders** [comment]
We do recognize this parameters:
tls=true
truststore=...
truststorepassword=...
The last two we add to Java System.properties().
You can also check this article. Our driver is using the MongoDB native driver.
https://www.mongodb.com/docs/drivers/java/sync/current/fundamentals/connection/tls/
