### ISSUE TITLE
Can not download JDBC driver binary distribution

### ISSUE THREAD

**Issue by DoubleCorner** [wise-coders/mongodb-jdbc-driver#17]
Download JDBC Driver Binary Distribution 
URL is invalid ? (http://www.dbschema.com/jdbc-drivers/MongoDbJdbcDriver.zip)

**Comment by wise-coders** [comment]
If I test this URL, for me it is working fine.
Do you get any error if you click this link? Can you please post a screenshot?

Best regards,
 Dragos Pruteanu

**Comment by DoubleCorner** [comment]
use safari is ok, but chrome is can not open

**Comment by wise-coders** [comment]
Interesting, for me it works fine under chrome. It is asking to download the file.

Best regards,
 Dragos Pruteanu

> On Friday, September 8, 2023 at 8:43:09 AM, DaveDevelop wrote:
>
> use safari is ok, but chrome is can not open
> —
> Reply to this email directly, [1] view it on GitHub, or [2] unsubscribe.
> You are receiving this because you commented.Message ID:

[1] https://github.com/wise-coders/mongodb-jdbc-driver/issues/17#issuecomment-1711158787
