### ISSUE TITLE
Supply tar distribution

### ISSUE THREAD

**Issue by devamondos** [wise-coders/mongodb-jdbc-driver#3]
Any chance we can get the jars in a tar distribution as well?

The reason being is that I want to gain access to it in [this docker image](https://www.docker.elastic.co/r/logstash) using a startup script.

Weirdly tar is available as a tool, but unzip isn't. While yum exists, sudo doesn't so I am unable to download them.

I am aware I can create my own Dockerfile where this wouldn't be an issue as I'd use this as a base image, but I'm trying to avoid that.

**Comment by wise-coders** [comment]
Wouldn't it work to use a simple script like in this post to transform it?

[1] https://unix.stackexchange.com/questions/146264/is-there-a-way-to-convert-a-zip-to-a-tar-without-extracting-it-to-the-filesystem

We do deploy the zip here:
[2] https://dbschema.com/jdbc-drivers/MongoDbJdbcDriver.zip

Best regards,
 Dragos Pruteanu

--
 DbSchema - Wise Coders GbmH
82256 Fürstenfeldbruck bei München
 Email: support@dbschema.com - Web: [3] http://dbschema.com/

--

[1] https://unix.stackexchange.com/questions/146264/is-there-a-way-to-convert-a-zip-to-a-tar-without-extracting-it-to-the-filesystem
[2] https://dbschema.com/jdbc-drivers/MongoDbJdbcDriver.zip
[3] http://www.example.com/

**Comment by devamondos** [comment]
The reason I was asking for a tar distribution is simply that it's the easiest way it will work with the tools that I have available on the Docker image startup script ([tar](https://man7.org/linux/man-pages/man1/tar.1.html) and not [unzip](https://linux.die.net/man/1/unzip), unable to use yum). Yes I can transform the tar to zip, but I would have to host the new tar file so that it would be available to the startup script. 

However, I have created a Dockerfile that does all this for me, but it's just not ideal as I want to deploy this on OpenShift. So I will have either need a git repo to build from source or build the new Dockerfile and host on a private docker registry.

I can for sure work around this, so I'm okay for this to be closed if it's not going to happen.

**Comment by devamondos** [comment]
That'll teach me for not reading your reply properly. Just used your first point using Python and managed to get it working. Thanks for helping and sorry for not reading it properly the first time

**Comment by wise-coders** [comment]
We added right now also a tar task to the build.gradle. Maybe this also helps.

Best regards,
 Dragos Pruteanu

--
 DbSchema - Wise Coders GbmH
82256 Fürstenfeldbruck bei München
 Email: support@dbschema.com - Web: [1] http://dbschema.com/

--

[1] http://www.example.com/
