### ISSUE TITLE
upgrade mongodb driver

### ISSUE THREAD

**Issue by nullren** [wise-coders/mongodb-jdbc-driver#6]
any chance we can get the underlying java mongodb driver upgraded? https://github.com/wise-coders/mongodb-jdbc-driver/blob/master/build.gradle#L22

4.3 or above is required for mongodb serverless. IntelliJ uses this driver to connect to mongodb, so without an upgrade, I am unable to connect to mongodb from IntelliJ.

thanks!

**Comment by wise-coders** [comment]
I am a bit confused here. Searching on maven central I find the latest release being 3.12.10:
![image](https://user-images.githubusercontent.com/60284259/142147097-95b4dafa-f32f-411b-9ae3-1944f9de31fa.png)

I found a 4.3 for the mongodb-driver-core, which shouldn't be used directly. 
Could you please check this?
If possible, please send us also the JDBC URL to connect to a serverless environment. We would add it in DbSchema JDBC URL pattern list.

**Comment by bigboNed3** [comment]
> 

I think [mongodb-driver-legacy](https://mvnrepository.com/artifact/org.mongodb/mongodb-driver-legacy) is what should be used. but it has some compatibility issues with current code base.

**Comment by bigboNed3** [comment]
or [mongodb-driver-sync](https://mvnrepository.com/artifact/org.mongodb/mongodb-driver-sync). which is recommended

**Comment by wise-coders** [comment]
Thank you for writing about this. We have upgraded the driver right today. 
You can download it from the website or delete the folder C:\Users\<YourUser>\.DbSchema\drivers\MongoDb
and DbSchema will automatically download the latest driver from the website.

I have one question, maybe you can help us.
We include in DbSchema a number of pre-build URLs. But I think we should extend this list, also with mongo+srv or others. Could you please review this list and let us know if we should extend it? I ask as I think you are working with MongoDB.

```
        <driver cls="com.dbschema.MongoJdbcDriver" url="mongodb://{HOST}:{PORT}[/{DB}]" authenticate="false" description="No Authentication" website="https://docs.mongodb.com/manual/reference/connection-string/"/>
        <driver cls="com.dbschema.MongoJdbcDriver" url="mongodb://{HOST}:{PORT}[/{DB}]?scan=full" authenticate="false" description="No Authentication, Full Scan" website="https://docs.mongodb.com/manual/reference/connection-string/"/>
        <driver cls="com.dbschema.MongoJdbcDriver" url="mongodb://{USER}:{PASSWORD}@{HOST}:{PORT}/{DB}?authSource={DB}&amp;connectTimeoutMS=1000" description="Password Authentication" website="https://docs.mongodb.com/manual/reference/connection-string/"/>
        <driver cls="com.dbschema.MongoJdbcDriver" url="mongodb://{USER}:{PASSWORD}@{HOST}:{PORT}/{DB}?authSource={DB}&amp;connectTimeoutMS=1000&amp;scan=full" description="Password Authentication, Full Scan" website="https://docs.mongodb.com/manual/reference/connection-string/"/>
        <driver cls="com.dbschema.MongoJdbcDriver" url="mongodb://{USER}:{PASSWORD}@{HOST}:{PORT}/{DB}?authSource={DB}&amp;authMechanism=SCRAM-SHA-1" description="SCRAM-SHA-1 Authentication" website="https://docs.mongodb.com/manual/reference/connection-string/"/>
        <driver cls="com.dbschema.MongoJdbcDriver" url="mongodb://{USER}:{PASSWORD}@{HOST}:{PORT}/{DB}?authSource={DB}&amp;authMechanism=MONGODB-CR" description="MONGODB-CR Authentication" website="https://docs.mongodb.com/manual/reference/connection-string/"/>
        <driver cls="com.dbschema.MongoJdbcDriver" url="mongodb://{USER}:{PASSWORD}@{HOST}:{PORT}/{DB}?authMechanism=MONGODB-X509&amp;ssl=true" description="X.509 Authentication" website="https://docs.mongodb.com/manual/reference/connection-string/"/>
        <driver cls="com.dbschema.MongoJdbcDriver" url="mongodb://{USER}@{HOST}:{PORT}/{DB}?authSource={DB}&amp;authMechanism=GSSAPI" description="Kerberos Authentication" website="https://docs.mongodb.com/manual/reference/connection-string/"/>
        <driver cls="com.dbschema.MongoJdbcDriver" url="mongodb://{USER}@{HOST}:{PORT}/{DB}?authSource=$external&amp;authMechanism=PLAIN" description="LDAP Authentication" website="https://docs.mongodb.com/manual/reference/connection-string/"/>
```

Also, any feedback about the driver is welcome.
